### ISSUE TITLE
RangeError related to JSDoc

### ISSUE THREAD

**Issue by Sebastian-G** [openlayers/openlayers#10950]
**Describe the bug**
We are using Angular 9,`jest@25.0.0`, `typescript@3.8.3` and latest `ol@6.3.1`

While running our unit tests following error occurred:
```
RangeError: Maximum call stack size exceeded
          at getTypeOfFuncClassEnumModule (node_modules/typescript/lib/typescript.js:41221:46)
          at getTypeOfSymbol (node_modules/typescript/lib/typescript.js:41342:24)
          at getTypeFromJSDocValueReference (node_modules/typescript/lib/typescript.js:44313:33)
          at getTypeReferenceType (node_modules/typescript/lib/typescript.js:44293:33)
          at getTypeFromJSDocValueReference (node_modules/typescript/lib/typescript.js:44329:36)
          at getTypeReferenceType (node_modules/typescript/lib/typescript.js:44293:33)
          at getTypeFromJSDocValueReference (node_modules/typescript/lib/typescript.js:44329:36)
          at getTypeReferenceType (node_modules/typescript/lib/typescript.js:44293:33)
          at getTypeFromJSDocValueReference (node_modules/typescript/lib/typescript.js:44329:36)
          at getTypeReferenceType (node_modules/typescript/lib/typescript.js:44293:33)
```

**To Reproduce**
1. Run JEST unit tests
2. See error: (see above)

This error doesn't occur on build, only while testing it.

**Comment by Schwobaland** [comment]
@Sebastian-G did you find a solution? Have the same setup - and same error :(

**Comment by Sebastian-G** [comment]
@Schwobaland not yet :cry:
