### ISSUE TITLE
getting error when running app

### ISSUE THREAD

**Issue by danielicy** [openlayers/openlayers#11240]
Hi I installed open layers following the instructions
but when I try to start it I get this:
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\Workspace\OpenLayers\openlayers
(node:20780) Warning: require() of ES modules is not supported.
require() of D:\Workspace\OpenLayers\openlayers\node_modules\rollup\dist\es\rollup.browser.js from D:\Workspace\OpenLayers\openlayers\tasks\serialize-workers.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename rollup.browser.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\Workspace\OpenLayers\openlayers\node_modules\rollup\dist\es\package.json.
× ｢wdm｣:    835 modules

ERROR in ../src/ol/worker/webgl.js
Module build failed (from ./webpack/worker-loader.js):
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\Workspace\OpenLayers\openlayers\node_modules\rollup\dist\es\rollup.browser.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Workspace\OpenLayers\openlayers\tasks\serialize-workers.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Workspace\OpenLayers\openlayers\examples\webpack\worker-loader.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)

ERROR in ../src/ol/worker/version.js
Module build failed (from ./webpack/worker-loader.js):
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\Workspace\OpenLayers\openlayers\node_modules\rollup\dist\es\rollup.browser.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Workspace\OpenLayers\openlayers\tasks\serialize-workers.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Workspace\OpenLayers\openlayers\examples\webpack\worker-loader.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
i ｢wdm｣: Failed to compile.

**Comment by danielicy** [comment]
fixed it!
uninstalled node (was using version 13.x)
and reinstalled (v12.18.2) and everything works!
