### ISSUE TITLE
error npm

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#11289]
Hi 
I get this when i try to follow the developing guide ... As i am really beginner with this environment i have any idea of what is wrong ...

Thank for any advice

**Result in my terminal**
```
jpb@PowerBookSSDjpb ~ % cd ~/Documents/developpement/GitHub/openlayers
jpb@PowerBookSSDjpb openlayers % npm run serve-examples

> ol@6.3.2-dev serve-examples /Users/jpb/Documents/developpement/GitHub/openlayers
> webpack-dev-server --config examples/webpack/config.js --mode development --watch

/Users/jpb/Documents/developpement/GitHub/openlayers/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:30
		} catch {}
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jpb/Documents/developpement/GitHub/openlayers/node_modules/terser-webpack-plugin/dist/index.js:26:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ol@6.3.2-dev serve-examples: `webpack-dev-server --config examples/webpack/config.js --mode development --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ol@6.3.2-dev serve-examples script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jpb/.npm/_logs/2020-07-17T19_34_13_350Z-debug.log

```

**Comment by ahocevar** [comment]
First of all, check that you are running a recent version of Node:

    node --version

The exception you are seeing makes me think you are using a version older than 10. But you should have version 12 or greater. You can fix this issue by installing node >= 12.

I would recommend using [nvm](https://github.com/nvm-sh/nvm) for installing and managing node versions.

**Comment by jipexu** [comment]
jpb@PowerBookSSDjpb openlayers % node -v
v12.18.2

??

**Comment by ahocevar** [comment]
Installing nvm is a good idea. With v12, you should really not be getting the above error.

**Comment by jipexu** [comment]
@ahocevar  thanks i remove the folder node_modules redo npm install and npm run serve-examples and work @ http://localhost:8081/
thanks
