### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#12127]
**Describe the bug**
Running `npm start` fails with the latest packages (178221e6913b54a1cb4b7be0dae3d5b8f2177f7a).

**To Reproduce**
1. `git fetch openlayers && git checkout main && git reset --hard openlayers/main`
2. `npm install && npm start`
3. See a stack trace like the one below

```
ERROR in ../src/ol/worker/webgl.js
Module build failed (from ./webpack/worker-loader.js):
Error: [BABEL]: Cannot find module '@babel/helper-define-map'
Require stack:
- /Users/tschaub/projects/openlayers/node_modules/@babel/plugin-transform-classes/lib/transformClass.js
- /Users/tschaub/projects/openlayers/node_modules/@babel/plugin-transform-classes/lib/index.js
- /Users/tschaub/projects/openlayers/node_modules/@babel/preset-env/lib/available-plugins.js
- /Users/tschaub/projects/openlayers/node_modules/@babel/preset-env/lib/plugins-compat-data.js
- /Users/tschaub/projects/openlayers/node_modules/@babel/preset-env/lib/normalize-options.js
- /Users/tschaub/projects/openlayers/node_modules/@babel/preset-env/lib/index.js
- /Users/tschaub/projects/openlayers/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/tschaub/projects/openlayers/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/tschaub/projects/openlayers/node_modules/@babel/core/lib/config/files/index.js
- /Users/tschaub/projects/openlayers/node_modules/@babel/core/lib/index.js
- /Users/tschaub/projects/openlayers/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js
- /Users/tschaub/projects/openlayers/tasks/serialize-workers.js
- /Users/tschaub/projects/openlayers/examples/webpack/worker-loader.js
- /Users/tschaub/projects/openlayers/node_modules/loader-runner/lib/loadLoader.js
- /Users/tschaub/projects/openlayers/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/tschaub/projects/openlayers/node_modules/webpack/lib/NormalModule.js
- /Users/tschaub/projects/openlayers/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/tschaub/projects/openlayers/node_modules/webpack/lib/Compiler.js
- /Users/tschaub/projects/openlayers/node_modules/webpack/lib/webpack.js
- /Users/tschaub/projects/openlayers/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/tschaub/projects/openlayers/node_modules/webpack-cli/lib/bootstrap.js
- /Users/tschaub/projects/openlayers/node_modules/webpack-cli/bin/cli.js
- /Users/tschaub/projects/openlayers/node_modules/webpack/bin/webpack.js (While processing: /Users/tschaub/projects/openlayers/node_modules/@babel/preset-env/lib/index.js)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/tschaub/projects/openlayers/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/tschaub/projects/openlayers/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:14:41)
    at Module._compile (/Users/tschaub/projects/openlayers/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/tschaub/projects/openlayers/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/tschaub/projects/openlayers/node_modules/@babel/plugin-transform-classes/lib/index.js:20:46)
    at Module._compile (/Users/tschaub/projects/openlayers/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

**Expected behavior**
`npm start` should run without errors.

**Comment by tschaub** [comment]
I take that back.  It looks like things resolved themselves after another `npm install`.
