### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by taoqf** [openlayers/openlayers#12525]
**Describe the bug**
I have a next.js project, when I use ol in the page. exception throws.

```log
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /myprj/node_modules/ol/index.js
require() of ES modules is not supported.
require() of /myprj/node_modules/ol/index.js from /myprj/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /myprj/node_modules/ol/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /myprj/node_modules/ol/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1154:13)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.ol (/myprj/.next/server/pages/index.js:55:18)
    at __webpack_require__ (/myprj/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/index/main.tsx:7:60)
    at Object../src/pages/index/main.tsx (/myprj/.next/server/pages/index.js:33:1)
    at __webpack_require__ (/myprj/.next/server/webpack-runtime.js:33:42) {
  code: 'ERR_REQUIRE_ESM'
}
```

**To Reproduce**
1. create a next.js project
2. create a page
3. add ol in it.

**Expected behavior**

https://github.com/openlayers/openlayers/issues/11240

according to this, I downgraded node to 12.18.2, nothing helps.

**Comment by ahocevar** [comment]
Do you have `const ... = require('ol')` in your project? You need to change that to `import {...} from 'ol'`. And it cannot hurt to upgrade to the stable Node version (16).

**Comment by taoqf** [comment]
No. I didn't. This seems an issue of next.js. I solved with [this](https://github.com/vercel/next.js/issues/23725#issuecomment-863158509)

**Comment by taoqf** [comment]
And I searched, find any require in any file. I didn't know why this error came out.

**Comment by ziyue5** [comment]
> No. I didn't. This seems an issue of next.js. I solved with [this](https://github.com/vercel/next.js/issues/23725#issuecomment-863158509)

Hi, did you just substitute that three packages with OpenLayers? Are there any other changes needed? Thanks!
