### ISSUE TITLE
import a DOM-centric library in a non-DOM environment, even if it doesn't do anything

### ISSUE THREAD

**Issue by lhapaipai** [openlayers/openlayers#12641]
**Describe the bug**
I try to import OpenLayers in a SvelteKit App.
Because some browser specific code is declared in the module and not inside exported functions, the boundler (vitejs) which parses server-side code throws exceptions.

it is possible to bypass this problem with a dynamic import sveltejs/kit#779 but I think it may be interesting to clean the code of these side effects ?

```console
$ npx envinfo --system --npmPackages svelte,@sveltejs/kit,ol --binaries --browsers

  System:
    OS: Linux 5.12 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 944.56 MB / 15.58 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.10 - /usr/local/lib/node/bin/yarn
    npm: 7.20.6 - ~/.nvm/versions/node/v16.1.0/bin/npm
  Browsers:
    Chromium: 91.0.4472.164
    Firefox: 90.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.154 
    ol: ^6.6.1 => 6.6.1 
    svelte: ^3.34.0 => 3.42.1 
```

1. create a sveltekit project `npm init svelte@latest` : skeleton / no typescript / no eslint / no prettier / `cd <project> && npm i && npm i ol`
2. create a simple map inside `src/routes/index.svelte`

```svelte
<script>
  import "ol/ol.css";
  import { Map, View } from "ol";
  import OSM from "ol/source/OSM";

  import {Tile as TileLayer, Group} from "ol/layer";
  import { fromLonLat } from "ol/proj";
  import { onMount } from "svelte";

  onMount(() => {

    const map = new Map({
      layers: [
        new Group({
          layers: [
            new TileLayer({
              source: new OSM()
            })
          ]
        })
      ],
      target: "map",
      view: new View({
        center: fromLonLat([5.37, 43.2951]),
        zoom: 10
      })
    });

  });
</script>

<div id="map" />

<style>
  #map {
    width: 600px;
    height: 400px;
  }
</style>

```

3. run dev server : `npm run dev`
```console
> svelte-kit dev


  SvelteKit v1.0.0-next.154

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network


17:56:15 [vite] Error when evaluating SSR module /node_modules/ol/worker/webgl.js:
ReferenceError: Blob is not defined
    at ../src/worker/webgl.js:3:25
    at instantiateModule (~/svelte-ol/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:73866:15)
17:56:15 [vite] Error when evaluating SSR module /node_modules/ol/renderer/webgl/PointsLayer.js:
ReferenceError: Blob is not defined
    at ../src/worker/webgl.js:3:25
    at instantiateModule (~/svelte-ol/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:73866:15)
17:56:15 [vite] Error when evaluating SSR module /node_modules/ol/layer/Heatmap.js:
ReferenceError: Blob is not defined
    at ../src/worker/webgl.js:3:25
    at instantiateModule (~/svelte-ol/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:73866:15)
17:56:15 [vite] Error when evaluating SSR module /node_modules/ol/layer.js:
ReferenceError: Blob is not defined
    at ../src/worker/webgl.js:3:25
    at instantiateModule (~/svelte-ol/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:73866:15)
17:56:15 [vite] Error when evaluating SSR module ~/svelte-ol/src/routes/index.svelte:
ReferenceError: Blob is not defined
    at ../src/worker/webgl.js:3:25
    at instantiateModule (~/svelte-ol/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:73866:15)
Blob is not defined
ReferenceError: Blob is not defined
    at ../src/worker/webgl.js:3:25
    at instantiateModule (~/svelte-ol/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:73866:15)
```

**Expected behavior**
No compilation Error from Vite dev server

the beginning of a solution would come from the serialize-workers task  `serialize-workers.cjs` which uses the Blob class 
https://github.com/openlayers/openlayers/blob/2dd212cdac93200a1f64b092fdb377594ec6ed5d/tasks/serialize-workers.cjs#L47

```js
 //...

  plugins.push({
    name: "serialize worker and export create function",
    renderChunk(code) {
      return `
        const source = ${JSON.stringify(code)};
        let blob;
        let url;
        export function create() {
          if (!blob) {
            blob = new Blob([source], {type: 'application/javascript'});
            url = URL.createObjectURL(blob);
          }
          return new Worker(url);
        }
      `;
    },
  });

//...
```
but the development server still fails to compile .

**Comment by adminy** [comment]
Same issue here:
```
10:43:58 AM [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "ol/renderer/webgl/VectorLayer.js"
|- ReferenceError: Worker is not defined
    at create (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/ol/worker/webgl.js:4:11)
    at file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/ol/render/webgl/VectorStyleRenderer.js:21:22
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async nodeImport (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/vite/dist/node/chunks/dep-df561101.js:56019:17)
    at async ssrImport (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:24)
    at async eval (/Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/src/routes/+page.svelte:17:32)
    at async instantiateModule (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)

Internal server error: Worker is not defined
      at create (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/ol/worker/webgl.js:4:11)
      at file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/ol/render/webgl/VectorStyleRenderer.js:21:22
      at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
      at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
      at async nodeImport (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/vite/dist/node/chunks/dep-df561101.js:56019:17)
      at async ssrImport (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:24)
      at async eval (/Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/src/routes/+page.svelte:17:32)
      at async instantiateModule (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)
ReferenceError: Worker is not defined
    at create (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/ol/worker/webgl.js:4:11)
    at file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/ol/render/webgl/VectorStyleRenderer.js:21:22
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async nodeImport (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/vite/dist/node/chunks/dep-df561101.js:56019:17)
    at async ssrImport (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:24)
    at async eval (/Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/src/routes/+page.svelte:17:32)
    at async instantiateModule (file:///Users/adminy/Downloads/2210150-734df560abcf6374bd28f8c515eb59a73e174487/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)
```
