### ISSUE TITLE
Error in accessing map object

### ISSUE THREAD

**Issue by mrajasekar87** [openlayers/openlayers#13067]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

-----------------------------------------Code Start -------------------------------------------------------
import "ol/ol.css";
import Map from "ol/Map";
import TileLayer from "ol/layer/Tile";
import View from "ol/View";
import OSM from "ol/source/OSM";
import TileDebug from "ol/source/TileDebug";

const map = new Map({
  layers: [
    new TileLayer({
      source: new OSM()
    }),
    new TileLayer({
      source: new TileDebug()
    })
  ],
  target: "map",
  view: new View({
    center: [0, 0],
    zoom: 1
  })
});

console.log(map);

-----------------------------------------Code End -------------------------------------------------------

-----------------------------------------Error Start -------------------------------------------------------

TypeError: e.forEach is not a function
    at Object.toSerializable (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:7616)

    at e._applyTransform (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:10039)

    at e._handleValue (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:11382)

    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:10263)

    at e._handleArray (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:10334)

    at e._handleObject (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:10848)

    at e._handleValue (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:11421)

    at a (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:10488)

    at e._handlePlainObject (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:10556)

    at e._handleObject (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:10869)

    at e._handleValue (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:11421)

    at e.transform (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:11622)

    at e.encode (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:16487)

    at Object.t.Encode (https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:9021)

    at https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:710

-----------------------------------------Error End-------------------------------------------------------

**Comment by tschaub** [comment]
The `ol/source/DataTile` source can only be used with the `ol/layer/WebGLTile` layer currently.  See this example: https://openlayers.org/en/latest/examples/data-tiles.html or this code sandbox: https://codesandbox.io/s/c4t5i

**Comment by mike-000** [comment]
@tschaub There is no `ol/source/DataTile` in the code above.  Adding `console.log(map);` to your codesandbox (or any other example codesandbox going back to OpenLayers 5.0.0) produces the same message in the codesandbox console (even after setting a timeout), but it is logged correctly in the browser console.  It seems like a codesandbox internal error when logging certain objects.

**Comment by tschaub** [comment]
Thanks for the correction, @mike-000.  I read `TileDebug` as `DataTile`.
