### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by pankaj-bansal** [openlayers/openlayers#1352]
Hi

I am having errors while building the ol3. I have installed all the things mentioned in the requirement.txt. I have installed GIT and checked out the code. I am getting following error. 

Traceback (most recent call last):
  File "build.py", line 83, in <module>
    '%(GIT)s', 'rev-parse', '--abbrev-ref', 'HEAD').strip()
  File "C:\Users\Virendra\Downloads\ol3-master\ol3-master\pake.py", line 348, in
 output
    return check_output(args)
  File "c:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, _popenargs, *_kwargs)
  File "c:\Python27\lib\subprocess.py", line 709, in **init**
    errread, errwrite)
  File "c:\Python27\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

Any help please. I am stuck on this.

Regards
Pankaj Bansal

**Comment by gdini** [comment]
Hi,
I am facing the same issue as pankaj-bansal. I can't get rid of the windowserror[error 2].
Could you please share your solution? How did you arrange the git path to make it work?
