### ISSUE TITLE
WFS 1.1.0 writeGetFeature with resourceId filter do not work

### ISSUE THREAD

**Issue by bjornharrtell** [openlayers/openlayers#14833]
Causes crash deep in XML serialization:
```
	TypeError: Cannot read properties of undefined (reading 'call')
	    at serialize (/tmp/_karma_webpack_144391/webpack:/ol/src/ol/xml.js:479:1)
	    at pushSerializeAndPop (/tmp/_karma_webpack_144391/webpack:/ol/src/ol/xml.js:523:1)
	    at writeFilterCondition (/tmp/_karma_webpack_144391/webpack:/ol/src/ol/format/WFS.js:1066:22)
	    at writeQuery (/tmp/_karma_webpack_144391/webpack:/ol/src/ol/format/WFS.js:1052:1)
	    at /tmp/_karma_webpack_144391/webpack:/ol/src/ol/xml.js:273:1
	    at serialize (/tmp/_karma_webpack_144391/webpack:/ol/src/ol/xml.js:479:1)
	    at pushSerializeAndPop (/tmp/_karma_webpack_144391/webpack:/ol/src/ol/xml.js:523:1)
	    at writeGetFeature (/tmp/_karma_webpack_144391/webpack:/ol/src/ol/format/WFS.js:1354:22)
	    at WFS.writeGetFeature (/tmp/_karma_webpack_144391/webpack:/ol/src/ol/format/WFS.js:538:1)
	    at Context.<anonymous> (/tmp/_karma_webpack_144391/webpack:/ol/test/browser/spec/ol/format/wfs.test.js:1943:52)
```

**Comment by bjornharrtell** [comment]
Closing as I do not anticipate that I or anyone else will find it worthwhile to improve the error handling at this point.
