### ISSUE TITLE
Using Bun - TypeError: null is not an object (evaluating 'sourceProjection.getCode')

### ISSUE THREAD

**Issue by cyrus01337** [openlayers/openlayers#15125]
**Describe the bug**
Unable to use `toLonLat` on the server, specifically a script run via Bun.

Error in question:
```js
459 |  */
460 | export function getTransformFromProjections(
461 |   sourceProjection,
462 |   destinationProjection
463 | ) {
464 |   const sourceCode = sourceProjection.getCode();
                         ^
TypeError: null is not an object (evaluating 'sourceProjection.getCode')
      at getTransformFromProjections (/home/cyrus/project/node_modules/ol/proj.js:464:21)
      at transform (/home/cyrus/project/node_modules/ol/proj.js:504:24)
      at toLonLat (/home/cyrus/project/node_modules/ol/proj.js:417:17)
      at arrangeArrayStupidly (/home/cyrus/project/main.js:19:21)
      at main.js:34:25
```
Line 34 being:
```js
const converted = toLonLat([327828.613, 373756.171], "EPSG:27700");
```

**To Reproduce**
1. Import `toLonLat` from `ol/proj`
2. Try to use it on a server-side script using Bun
3. See error

**Expected behavior**
`toLonLat` and similar functions should run, unsure what has caused this as it works fine on the browser.

**Comment by cyrus01337** [comment]
I feel silly for only now seeing this example, I would not have known where to get such projection data. For future reference, where can I retrieve this?

On a slight tangent, is it possible for a meaningful exception to be raised when attempting to use an unreigstered projection?

**Comment by cyrus01337** [comment]
To clarify, yes, that did help and now my script runs as intended. :)

**Comment by ahocevar** [comment]
@cyrus01337 There is always a trade-off between not increasing the library size too much with checks and meaningful error messages. In this specific case, we could throw a meaningful exception in `getProjection(code)` when the lookup for `code` fails. Would you be willing to create a pull request?

**Comment by cyrus01337** [comment]
@ahocevar That is fair, mostly thinking from a DX perspective anyways as this error threw me through a loop for quite some time now. I wouldn't mind giving it a try, will need to look through source to find that function first though. Will sort soon. :)
@M393 This was helpful, thanks a lot for this!
