### ISSUE TITLE
Uncaught TypeError: source.getGetFeatureInfoUrl is not a function

### ISSUE THREAD

**Issue by prosperva** [openlayers/openlayers#15140]
`Open layers 8.1.0`

I have the following code:

```
mapObject.on("singleclick", function (evt) {
      let view = mapObject.getView();
      let viewResolution = view.getResolution();
      let layers: any = mapObject.getLayers();

      layers.forEach(function (elem: any) {
        if (elem.get("visible")) {
          var source = elem.getSource();

          var url = source.getGetFeatureInfoUrl(
            evt.coordinate,
            viewResolution,
            projection,
            {
              INFO_FORMAT: "application/json",
              FEATURE_COUNT: 25,
            }
          );
          console.log(url);
        }
      });
    });
```
The source comes back fine but the console.log says this when I try to access the `getGetFeatureInfoUrl`

`Uncaught TypeError: source.getGetFeatureInfoUrl is not a function`

The layer shows up on the map.

**Comment by MoonE** [comment]
The function has been renamed in version 6.0.0 to `getFeatureInfoUrl`
See https://github.com/openlayers/openlayers/releases/tag/v6.0.0

**Comment by prosperva** [comment]
I just changed it to `getFeatureInfoUrl` and I am getting the same error

**Comment by MoonE** [comment]
Are you certain the source is either `ol/source/ImageWMS` or `ol/source/TileWMS`? Other sources do not have this function.

**Comment by prosperva** [comment]
Yes this is how I am creating it:

```
let layer = new ImageLayer({
      properties: {
        id: 'test',
      },
      visible: visible,
      source: new ImageWMS({
        url: 'layerUrl',
        params:{},
      }),
    });
```

**Comment by prosperva** [comment]
Complete error:

```
TypeError: source.getFeatureInfo is not a function
    at index.tsx:54:1
    at Collection.forEach (Collection.js:156:1)
    at Map.<anonymous> (index.tsx:50:1)
    at Map.dispatchEvent (Target.js:112:1)
    at Map.handleMapBrowserEvent (Map.js:1142:1)
    at MapBrowserEventHandler.dispatchEvent (Target.js:112:1)
    at MapBrowserEventHandler.js:153:1
```

**Comment by arekgotfryd** [comment]
Could you please share reproduction repo?

**Comment by prosperva** [comment]
https://stackblitz.com/edit/stackblitz-starters-xqsgb4?file=main.js

**Comment by ahocevar** [comment]
It‘s `source.getFeatureInfoUrl()`.

**Comment by prosperva** [comment]
Thanks @ahocevar. It works now
