### ISSUE TITLE
In vue, use version 9.1.0 to introduce import "ol/ol.css" and the console reports an error

### ISSUE THREAD

**Issue by mengpierde** [openlayers/openlayers#15771]
in ./node_modules/ol/ol.css

Module build failed: BrowserslistError: Unknown browser query `dead`
    at D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\autoprefixer\node_modules\browserslist\index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\autoprefixer\node_modules\browserslist\index.js:132:18)
    at browserslist (D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\autoprefixer\node_modules\browserslist\index.js:224:16)
    at Browsers.parse (D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\autoprefixer\lib\browsers.js:61:16)
    at new Browsers (D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\autoprefixer\lib\browsers.js:52:30)
    at loadPrefixes (D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\autoprefixer\lib\autoprefixer.js:70:24)
    at plugin (D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\autoprefixer\lib\autoprefixer.js:81:24)
    at LazyResult.run (D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:277:20)
    at LazyResult.asyncTick (D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:192:32)
    at LazyResult.asyncTick (D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:204:22)
    at D:\a_codeFile\sunDrilling\qdzj\drilling\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:197:27

 @ ./node_modules/ol/ol.css 4:14-109 13:3-17:5 14:22-117
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/index.vue
 @ ./src/components/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8081 webpack/hot/dev-server babel-polyfill ./src/main.js

**Comment by ahocevar** [comment]
Please provide a repository to reproduce the problem.
