### ISSUE TITLE
VectorTileLayer with no declutter causes error when another VectorTileLayer has declutter enabled

### ISSUE THREAD

**Issue by dchaps** [openlayers/openlayers#15849]
**Describe the bug**
Having a `VectorTileLayer` with `declutter:false` and another `VectorTileLayer` with `declutter:true` causes the below console error and the map is blank. The error is not caused when all `VectorTileLayer`'s are `declutter:false`. 

The bug appears to have been introduced in `9.2.0` as it does not cause an error with `9.1.0`

```
helpers.js:122 Uncaught TypeError: declutterTree.collides is not a function
    at Executor.execute_ (Executor.js:960:32)
    at Executor.execute (Executor.js:1262:10)
    at ExecutorGroup.execute (ExecutorGroup.js:412:20)
    at CanvasVectorTileLayerRenderer.postRender (VectorTileLayer.js:765:23)
    at CanvasVectorTileLayerRenderer.renderFrame (TileLayer.js:536:10)
    at VectorTileLayer.render (Layer.js:384:28)
    at CompositeMapRenderer.renderFrame (Composite.js:142:29)
    at Map.renderFrame_ (Map.js:1595:20)
    at Map.animationDelay_ (Map.js:1449:10)
    at sentryWrapped (helpers.js:100:17)
```

**To Reproduce**
1. Go to this [sandbox](https://codesandbox.io/p/sandbox/mapbox-vector-tiles-forked-cwc5dr)
2. Add your Mapbox api key
3. Change one of the `VectorTileLayer`'s to `false`
4. See the error in the console.

If the sandbox link does not work, it is a fork of the [Mapbox Vector Tiles](https://openlayers.org/en/latest/examples/mapbox-vector-tiles.html) example, with the layer duplicated. 

**Expected behavior**
No error and the map to be rendered.

**Comment by tschaub** [comment]
This is resolved in the `ol@9.2.3` release (thanks @ahocevar for the fix)
