### ISSUE TITLE
Error when getting attributions of a BingMaps layer

### ISSUE THREAD

**Issue by Akbalder** [openlayers/openlayers#15928]
**Describe the bug**
I sometimes have an error when getting the attributions of a BingMaps layer:
```
TypeError: Cannot read properties of undefined (reading '1')
    at BingMaps.js:315:43
    at Array.map (<anonymous>)
    at BingMaps.js:308:35
    at TileLayer.getAttributions (Layer.js:352:24)
```

When debugging, the coverrageArea object doesn't have a bbox property:
```json
{"zoomMin":1,"zoomMax":21,"jsonBoundingBox":[-90,-180,90,180],"boundingBox":{"northeast":{"type":"Point","coordinates":[90,180]},"southwest":{"type":"Point","coordinates":[-90,-180]},"southLatitude":-90,"westLongitude":-180,"northLatitude":90,"eastLongitude":180}}
```

**To Reproduce**
I don't know when this happen. It works correctly most of the time...

1. Add a BingMaps layer
2. In a 'postrender' event, call getAttributions on the BingMaps layer

**Expected behavior**
No error in the console

**Comment by bikulovIndor** [comment]
Hello, did you managed this problem somehow? I also faced it.

**Comment by Akbalder** [comment]
I didn't fix it. For me, the issue hasn't any consequence other than displaying an error in the console.

**Comment by robertpbaxter** [comment]
I investigated this issue in our own system and discovered that we are getting two separate formats in network responses from the map tiles request going out to `'https://dev.virtualearth.net/REST/v1/Imagery/Metadata/AerialWithLabelsOnDemand?...`. Same request each time, but the response sometimes differs/

A correct response looks like this:
```
{
                            "attribution": "© 2024 Microsoft Corporation",
                            "coverageAreas": [
                                {
                                    "bbox": [
                                        -90,
                                        -180,
                                        90,
                                        180
                                    ],
                                    "zoomMax": 21,
                                    "zoomMin": 1
                                }
                            ]
                        },
```

but one of the errors above happens when it sends over a completely different format:

```
{
                            "attribution": "© 2024 Microsoft Corporation",
                            "coverageAreas": [
                                {
                                    "zoomMin": 1,
                                    "zoomMax": 21,
                                    "jsonBoundingBox": [
                                        -90,
                                        -180,
                                        90,
                                        180
                                    ],
                                    "boundingBox": {
                                        "EastLongitude": 180,
                                        "NorthLatitude": 90,
                                        "SouthLatitude": -90,
                                        "WestLongitude": -180
                                    }
                                }
                            ]
                        },
```
