### ISSUE TITLE
WFS#writeTransaction() fails for undefined properties

### ISSUE THREAD

**Issue by m-elseberg** [openlayers/openlayers#15926]
The [`writeTransaction()`](https://openlayers.org/en/latest/apidoc/module-ol_format_WFS-WFS.html#writeTransaction) method of the `ol/format/WFS` class fails for features having `undefined` property values.

As an example, consider this snippet:

```js
import WFS from "ol/format/WFS";
import GML3 from "ol/format/GML3";
import Feature from "ol/Feature";

const wfs = new WFS({
    version: "2.0.0",
    gmlFormat: new GML3()
});

const feature = new Feature({
    someProperty: undefined
});

const transaction = wfs.writeTransaction([feature], [], [], {
    featurePrefix: "sf",
    featureNS: "http://www.openplans.org/spearfish",
    featureType: "bugsites",
    nativeElements: []
});
console.log("Transaction:", transaction);
```

Running the code fails with an error saying:

```
GML3.js:867 Uncaught TypeError: Cannot read properties of undefined (reading 'getSimplifiedGeometry')
    at wx.writeFeatureElement (GML3.js:867:67)
    at yT (WFS.js:806:21)
    at xml.js:273:16
    at np (xml.js:479:58)
    at rp (xml.js:523:3)
    at dT (WFS.js:724:3)
    at wb.format.WFS.writeTransaction (WFS.js:625:7)
```

Here's an excerpt from the [`writeFeatureElement()`](https://github.com/openlayers/openlayers/blob/main/src/ol/format/GML3.js#L844) method of the `GML3` class:

```js
writeFeatureElement(node, feature, objectStack) {
  /* ... */
  const properties = feature.getProperties();
  for (const key in properties) {
    const value = properties[key];
    if (value !== null) {
      keys.push(key);
      values.push(value);
      if (
        key == geometryName ||
        typeof (/** @type {?} */ (value).getSimplifiedGeometry) ===
          'function'
      ) {
        if (!(key in context.serializers[featureNS])) {
          context.serializers[featureNS][key] = makeChildAppender(
            this.writeGeometryElement,
            this,
          );
        }
      } else {
        if (!(key in context.serializers[featureNS])) {
          context.serializers[featureNS][key] =
            makeChildAppender(writeStringTextNode);
        }
      }
    }
  }
  /* ... */
}
```

Shouldn't the `value !== null` check be changed to `value != null`?

This occurs in OpenLayers v9.2.4.

**Comment by m-elseberg** [comment]
The issue continues to exist in OpenLayers v10.0.0. I opened a pull request to fix it: #16066.
