### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'wantedTiles')

### ISSUE THREAD

**Issue by FunnBobby** [openlayers/openlayers#16266]
**Describe the Bug:**

After upgrading to OpenLayers 10, we have experienced the following error:

**Error Message:**

TypeError: Cannot read properties of null (reading 'wantedTiles')
    at Array.postRenderFunction (TileLayer.js:847:38)
    at Map.handlePostRender (Map.js:1233:29)
    at Map.js:1643:14
    at timer (zone.js:1716:37)
    at _ZoneDelegate.invokeTask (zone.js:398:33)
    at core.mjs:14556:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:14556:36)
    at _ZoneDelegate.invokeTask (zone.js:397:38)
    at Object.onInvokeTask (core.mjs:14869:33)
    at _ZoneDelegate.invokeTask (zone.js:397:38)

_Downgrading to OpenLayers 7 makes the error go away._

**To Reproduce:**
_Steps to reproduce the behavior:_

Show OpenLayers (OL) tiles.

Hide OL tiles.

Show OL tiles again.

See the error.

**Expected Behavior:**

The expected behavior would be that of OpenLayers 7 where "wantedTiles" does not cause an error.

**Comment by ahocevar** [comment]
@FunnBobby Can you please provide more details on how you "hide OL tiles" and "show OL tiles" again?

**Comment by FunnBobby** [comment]
@ahocevar Essentially if I have a map that has many vector objects on it my application uses CSS classes to dynamically adjust the layout of an application, referred to as "app-part-a" and " map ". The . app-part-a class makes the main content fully visible by setting # app-part-a_content { width: 100%; } and hides the map content with #map_content { display: none; }. The .map-full class displays the map content in full width with #map_content { width: 100%; } and hides the main content using # app-part-a_content { display: none; }.  In this back and forth the wantedTiles error displays on OL 10 where it had not in OL 7 which is what I upgraded from.

**Comment by FunnBobby** [comment]
@ahocevar Thanks for the response but I'm not sure I understand...I'm using CSS to show and hide my map and don't believe I'm calling post-render functions?  If there is something I can call to stop post render functions from running please share and I'll be sure to try it.
