### ISSUE TITLE
ReferenceError: Worker is not defined when using WebGLVectorLayerRenderer

### ISSUE THREAD

**Issue by MarciaBM** [openlayers/openlayers#16271]
**Describe the bug**
I have a JS project with Next JS and when I use a WebGLVectorLayer created as you suggest, I get the following compilation error:

` ⨯ ReferenceError: Worker is not defined
    at __webpack_require__ (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/webpack-runtime.js:33:42)
    at eval (./src/components/Map1.js:15:87)
    at (ssr)/./src/components/Map1.js (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/app/page.js:140:1)
    at __webpack_require__ (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/page.js:10:74)
    at (ssr)/./src/app/page.js (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/app/page.js:129:1)
    at Object.__webpack_require__ [as require] (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/webpack-runtime.js:33:42)
digest: "2474330052"
 GET / 500 in 26087ms
`

**To Reproduce**
1. Go to a repository that I created: https://github.com/MarciaBM/openlayers-bug
2. Just run in dev
3. See error in the console

**Expected behavior**
No error

**Comment by jahow** [comment]
Hi,

Thank you for the reproduction repo! It seems like Next.js is trying to run the OL rendering code on the server even though you specified `'use client'` at the top of the Map1.js file. This is failing because the `Worker` class is not available globally in node.

This being said, it seems like there is another issue here: you're not giving any source to your WebGLLayer object. As such, the app still opens but the map on the left is empty.

**Comment by MarciaBM** [comment]
I know the source is empty, this was just to demonstrate the problem, with a non-empty source the bug still exists. I've also tried the next/dynamic ssr flag to false and nothing.

Do you have any idea of a workaround or something?

**Comment by jahow** [comment]
I tried on your repository to load the `WebGLVectorLayerRenderer` class through a dynamic import like so:
```js
    import('ol/renderer/webgl/VectorLayer').then(({ default: WebGLVectorLayerRenderer }) => {
      class WebGLLayer extends Layer {
        createRenderer() {
          return new WebGLVectorLayerRenderer(this, {
            style,
          });
        }
      }

     map1.addLayer(new WebGLLayer({}));

    // ...
```

and then, the ReferenceError goes away (presumably because Next.js doesn't try to resolve the module on the server side). This is a hacky workaround though, and I haven't spent much more time on this. Hope that helps!

**Comment by MarciaBM** [comment]
Thank you, meanwhile I found out that putting the class declaration in a separated file also makes the error disappear, I don't know why it happens though.

**Comment by wolfcreative** [comment]
Faced the same problem. I had to roll back to an older version
