### ISSUE TITLE
we should clear out the coverage directory

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#3506]
on npm run test-coverage otherwise errors will arise if files disappear from the repo

```
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/bartvandeneijnden/opengeo/git/ol3_bartvde/src/ol/render/ivectorcontext.js'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at LookupStore.Store.mix.get (/Users/bartvandeneijnden/opengeo/git/ol3_bartvde/node_modules/istanbul/lib/store/fslookup.js:40:19)
    at HtmlReport.Report.mix.writeDetailPage (/Users/bartvandeneijnden/opengeo/git/ol3_bartvde/node_modules/istanbul/lib/report/html.js:394:67)
    at /Users/bartvandeneijnden/opengeo/git/ol3_bartvde/node_modules/istanbul/lib/report/html.js:472:26
    at SyncFileWriter.extend.writeFile (/Users/bartvandeneijnden/opengeo/git/ol3_bartvde/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/Users/bartvandeneijnden/opengeo/git/ol3_bartvde/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /Users/bartvandeneijnden/opengeo/git/ol3_bartvde/node_modules/istanbul/lib/report/html.js:471:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/bartvandeneijnden/opengeo/git/ol3_bartvde/node_modules/istanbul/lib/report/html.js:465:23)
    at /Users/bartvandeneijnden/opengeo/git/ol3_bartvde/node_modules/istanbul/lib/report/html.js:467:22
```

cc @marcjansen

**Comment by marcjansen** [comment]
Good catch.
