### ISSUE TITLE
Infinite call stack when extending ol.source.XYZ with ol-debug.js (v3.5.0)

### ISSUE THREAD

**Issue by suguiura** [openlayers/openlayers#3730]
The problem can be reproduced with the following code, inspired by [osmsource](https://github.com/openlayers/ol3/blob/v3.5.0/src/ol/source/osmsource.js):

```
var MySource = function () {
    var url = 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    ol.source.XYZ.call(this, {url: url})
};
MySource.prototype = Object.create(ol.source.XYZ.prototype);
MySource.prototype.constructor = MySource;

var s = new MySource();
```

The lines where it happens:

```
(...)
at Object.goog.base (ol-3.5.0/ol-debug.js:2290:53)
at ol.source.XYZ.setTileUrlFunction (ol-3.5.0/ol-debug.js:113226:8)
at Object.goog.base (ol-3.5.0/ol-debug.js:2290:53)
at ol.source.XYZ.setTileUrlFunction (ol-3.5.0/ol-debug.js:113226:8)
(...)
```

**Comment by suguiura** [comment]
At `ol.source.XYZ.prototype.setTileUrlFunction`, `goog.base` calls `setTileUrlFunction` from the super class. Since `ol.source.XYZ` is `MySource` super class, `setTileUrlFunction` from `ol.source.XYZ` is called over and over.

The following code is a temporary workaround for this problem:

    ol.source.XYZ.prototype.setTileUrlFunction = function(tileUrlFunction) {
        var fn = ol.TileUrlFunction.withTileCoordTransform(this.tileCoordTransform_, tileUrlFunction);
        ol.source.TileImage.prototype.setTileUrlFunction.call(this, fn);
    };

(Calls `setTileUrlFunction` from `ol.source.TileImage` because it's `ol.source.XYZ` super class)

**Comment by suguiura** [comment]
Using `ol.inherits(MySource, ol.source.XYZ)` seems to be an "ol" way of solving this, but the method is marked as experimental. Thus, I'll leave this issue open for now.
