### ISSUE TITLE
require("openlayers") in Sublime3 

### ISSUE THREAD

**Issue by outlier888** [openlayers/openlayers#5440]
D:\work\GitHub\outlier\geojson-path-finder\node_modules\openlayers\dist\ol.js:131
{return!1}}(),ah="DeviceOrientationEvent"in qa,bh="geolocation"in qa.navigator
                                                                    ^
TypeError: Cannot use 'in' operator to search for 'geolocation' in undefined
    at D:\work\GitHub\outlier\geojson-path-finder\node_modules\openlayers\dist\ol.js:131:1082
    at OPENLAYERS (D:\work\GitHub\outlier\geojson-path-finder\node_modules\openlayers\dist\ol.js:7:22)
    at Object.<anonymous> (D:\work\GitHub\outlier\geojson-path-finder\node_modules\openlayers\dist\ol.js:13:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\work\GitHub\outlier\geojson-path-finder\mapindex.js:1:72)

**Comment by ahocevar** [comment]
This happens in all environments where the global is not a browser `window`. It should not be too hard to fix. There are a few more places where `goog.global` is assumed to be a `window` that would have to change. Pull request welcome.

**Comment by fredj** [comment]
`goog.global` not used anymore, closing
