### ISSUE TITLE
Error in build with webpack

### ISSUE THREAD

**Issue by juusechec** [openlayers/openlayers#6993]
I'm getting an error in webpack build. It is working with older version of OpenLayers and the same code.
```
+ npm run build

> openlayers-webpack@1.0.0 build /var/lib/jenkins/workspace/iliValidator/src/shapefile-viewer
> webpack --config webpack.config.js

Hash: 03d92a75f79ac197da79
Version: webpack 2.6.1
Time: 149922ms
                               Asset       Size  Chunks                    Chunk Names
0fa5c910d0f3f119cc8966ede7693ebc.gif      38 kB          [emitted]         
                           bundle.js     595 kB       0  [emitted]  [big]  app
                          styles.css    1.01 kB       0  [emitted]         app
                          index.html  767 bytes          [emitted]         
 [180] ./~/ol/view.js 35.8 kB {0} [built]
 [183] ./src/js/init/jquery.js 70 bytes {0} [built]
 [184] ./src/js/init/map.js 1.07 kB {0} [built]
 [185] ./src/js/init/material.js 111 bytes {0} [built]
 [186] ./src/js/init/shapefile.js 406 bytes {0} [built]
 [192] ./src/js/main.js 113 bytes {0} [built]
 [193] ./src/js/shapefile/popup.js 770 bytes {0} [built]
 [194] ./src/js/shapefile/subir.js 2.73 kB {0} [built]
 [197] ./src/css/map.css 41 bytes {0} [built]
 [198] ./src/css/popup.css 41 bytes {0} [built]
 [199] ./src/css/shapefile.css 41 bytes {0} [built]
 [230] ./~/jquery/src/jquery.js 640 bytes {0} [built]
 [242] ./~/material-design-lite/material.css 391 bytes {0} [built] [failed] [1 error]
 [243] ./~/material-design-lite/material.js 146 kB {0} [built]
 [329] ./~/ol/source/xyz.js 2.05 kB {0} [built]
    + 332 hidden modules

ERROR in ./~/ol/ol.css
Module parse failed: /var/lib/jenkins/workspace/iliValidator/src/shapefile-viewer/node_modules/ol/ol.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .ol-box {
|   box-sizing: border-box;
|   border-radius: 2px;
 @ ./src/js/init/map.js 1:0-20
 @ ./src/js/main.js

ERROR in ./~/material-design-lite/material.css
Module parse failed: /var/lib/jenkins/workspace/iliValidator/src/shapefile-viewer/node_modules/material-design-lite/material.css Unexpected character '@' (8:0)
You may need an appropriate loader to handle this file type.
|  * @link https://github.com/google/material-design-lite
|  */
| @charset "UTF-8";
| /**
|  * Copyright 2015 Google Inc. All Rights Reserved.
 @ ./src/js/init/material.js 1:0-44
 @ ./src/js/main.js
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] ./~/html-webpack-plugin/lib/loader.js!./src/views/index.html 1.05 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./src/img/ajax-loader.gif 82 bytes {0} [built]
       [2] ./~/base64-js/index.js 3.47 kB {0} [built]
       [3] ./~/buffer/index.js 48.6 kB {0} [built]
       [4] ./~/css-loader?{"minimize":true}!./src/css/shapefile.css 441 bytes {0} [built]
       [5] ./~/ieee754/index.js 2.05 kB {0} [built]
       [6] ./~/isarray/index.js 132 bytes {0} [built]
       [7] (webpack)/buildin/global.js 509 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.47 kB {0} [built]
       [2] ./~/buffer/index.js 48.6 kB {0} [built]
       [3] ./~/css-loader?{"minimize":true}!./src/css/map.css 246 bytes {0} [built]
       [4] ./~/ieee754/index.js 2.05 kB {0} [built]
       [5] ./~/isarray/index.js 132 bytes {0} [built]
       [6] (webpack)/buildin/global.js 509 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.47 kB {0} [built]
       [2] ./~/buffer/index.js 48.6 kB {0} [built]
       [3] ./~/css-loader?{"minimize":true}!./src/css/popup.css 828 bytes {0} [built]
       [4] ./~/ieee754/index.js 2.05 kB {0} [built]
       [5] ./~/isarray/index.js 132 bytes {0} [built]
       [6] (webpack)/buildin/global.js 509 bytes {0} [built]

npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! openlayers-webpack@1.0.0 build: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the openlayers-webpack@1.0.0 build script 'webpack --config webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openlayers-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openlayers-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openlayers-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/jenkins/workspace/iliValidator/src/shapefile-viewer/npm-debug.log

[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node

[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

```

The repository that I

 what to build with webpack is https://github.com/AgenciaImplementacion/shapefile-viewer/tree/1c73208187dc0a3f8ea2bb0506337458deea798c

This is npm-debug.log
```
-viewer/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle openlayers-webpack@1.0.0~prebuild: openlayers-webpack@1.0.0
6 silly lifecycle openlayers-webpack@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle openlayers-webpack@1.0.0~build: openlayers-webpack@1.0.0
8 verbose lifecycle openlayers-webpack@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle openlayers-webpack@1.0.0~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/lib/jenkins/workspace/iliValidator/src/shapefile-viewer/node_modules/.bin:/usr/bin:/sbin:/usr/sbin:/bin:/usr/bin
10 verbose lifecycle openlayers-webpack@1.0.0~build: CWD: /var/lib/jenkins/workspace/iliValidator/src/shapefile-viewer
11 silly lifecycle openlayers-webpack@1.0.0~build: Args: [ '-c', 'webpack --config webpack.config.js' ]
12 silly lifecycle openlayers-webpack@1.0.0~build: Returned: code: 2  signal: null
13 info lifecycle openlayers-webpack@1.0.0~build: Failed to exec build script
14 verbose stack Error: openlayers-webpack@1.0.0 build: `webpack --config webpack.config.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid openlayers-webpack@1.0.0
16 verbose cwd /var/lib/jenkins/workspace/iliValidator/src/shapefile-viewer
17 error Linux 3.10.0-514.16.1.el7.x86_64
18 error argv "/usr/bin/node" "/bin/npm" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error openlayers-webpack@1.0.0 build: `webpack --config webpack.config.js`
22 error Exit status 2
23 error Failed at the openlayers-webpack@1.0.0 build script 'webpack --config webpack.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the openlayers-webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --config webpack.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs openlayers-webpack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls openlayers-webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by juusechec** [comment]
I've solved removing line
```
exclude: /node_modules/,
```
Of
```
module: {
    rules: [{
      test: /\.(js|jsx)$/,
      use: 'babel-loader',
      exclude: path.resolve(__dirname, 'node_modules/')
    }, {
      test: /\.css$/,
      exclude: /node_modules/,
      use: ExtractTextPlugin.extract({
        use: [{
          loader: 'css-loader',
          options: {
            minimize: true
          }
        }]
      })
    }, {
      test: /\.(gif|png|jpg)$/,
      use: 'file-loader'
    }]
  },
```
