### ISSUE TITLE
build-ext.js - SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by aagg1234** [openlayers/openlayers#7076]
I try to use the version 4.2.0 of 'openlayers' in the project 'angular-openlayers-directive'.
During the travis build process at the project 'angular-openlayers-directive' i got a syntax error in file 'openlayers/tasks/build-ext.js'. You can see the interesting log lines down the issue.

Log lines of travis build process:

...
> openlayers@4.2.0 install /home/travis/build/tombatossals/angular-openlayers-directive/node_modules/openlayers
> node tasks/install.js
/home/travis/build/tombatossals/angular-openlayers-directive/node_modules/openlayers/tasks/build-ext.js:17
      let name = `ol.ext.${ext.name || ext.module}`;
      ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/tombatossals/angular-openlayers-directive/node_modules/openlayers/tasks/install.js:1:78)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by fredj** [comment]
Fixed with #6923
