### ISSUE TITLE
Failing ol.Sphere.getLength-test in Chrome 51.0.2704, GNU Linux

### ISSUE THREAD

**Issue by marcjansen** [openlayers/openlayers#7244]
For my setup the following test fails, while on CI it passes:

```
Chrome 51.0.2704 (Linux 0.0.0) ol.Sphere.getLength() works for case 2 FAILED
	Error: expected 4407939.1249141935 to equal 4407939.124914191
	    at Assertion.assert (/ol/node_modules/expect.js/index.js:96:13)
	    at Assertion.be.Assertion.equal (/ol/node_modules/expect.js/index.js:216:10)
	    at Context.<anonymous> (spec/ol/sphere.test.js:179:25)
```

Changing the expectation as follows fixes it.

```diff
diff --git a/test/spec/ol/sphere.test.js b/test/spec/ol/sphere.test.js
index bdc75c9..41e3fcc 100644
--- a/test/spec/ol/sphere.test.js
+++ b/test/spec/ol/sphere.test.js
@@ -176,7 +176,7 @@ describe('ol.Sphere.getLength()', function() {
     it('works for case ' + i, function() {
       var c = cases[i];
       var length = ol.Sphere.getLength(c.geometry, c.options);
-      expect(length).to.equal(c.length);
+      expect(length).to.roughlyEqual(c.length, 1e-8);
     });
   });
```

Is this a feasible change?

**Comment by ahocevar** [comment]
Yes, that's a feasible change. It's not the first time we see floating point and trigonometric operations differ a bit across platforms.
