### ISSUE TITLE
Custom Build Error with Darwin using 4.6.5

### ISSUE THREAD

**Issue by godlikemouse** [openlayers/openlayers#8168]
When following the custom build example I'm getting the following error when executing:

```
$ node tasks/build.js build/ol-custom.json build/ol-custom.js
module.js:341
    throw err;
    ^

Error: Cannot find module '../build/info.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/jasongraves/openlayers/node_modules/openlayers/tasks/generate-exports.js:64:19
    at /Users/jasongraves/openlayers/node_modules/async/dist/async.js:473:16
    at next (/Users/jasongraves/openlayers/node_modules/async/dist/async.js:5315:29)
    at /Users/jasongraves/openlayers/node_modules/async/dist/async.js:958:16
    at /Users/jasongraves/openlayers/node_modules/openlayers/tasks/generate-info.js:278:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

```

Everything is verbatim following the custom build examples.  I'm using the exact same ol-custom.json file:

```
{
  "exports": [
    "ol.Map",
    "ol.View",
    "ol.control.defaults",
    "ol.layer.Tile",
    "ol.source.OSM"
  ],
  "compile": {
    "externs": [
      "externs/bingmaps.js",
      "externs/cartodb.js",
      "externs/closure-compiler.js",
      "externs/esrijson.js",
      "externs/geojson.js",
      "externs/oli.js",
      "externs/olx.js",
      "externs/proj4js.js",
      "externs/tilejson.js",
      "externs/topojson.js"
    ],
    "extra_annotation_name": [
      "api", "observable"
    ],
    "compilation_level": "ADVANCED",
    "manage_closure_dependencies": true,
    "rewrite_polyfills": false
  }
}
```

I don't know how to progress forward from this point.  I've tried looking for an info.json which doesn't appear to exist in the node_modules/openlayers tree.  I found the tasks/generate-info.js which also doesn't appear to do anything from what I can tell.  Any assistance would be appreciated, thanks.

**Comment by ahocevar** [comment]
Custom builds won’t be supported in v5+ any more. Please consider building your application with imports from the ol package instead.

**Comment by godlikemouse** [comment]
Thank you.  Is there any documentation regarding current builds for minification, etc.?  Or should I just wait until the new v5 release is complete.

**Comment by ahocevar** [comment]
For documentation, please take a look at the instructions linked from https://npmjs.com/package/ol.

**Comment by godlikemouse** [comment]
Thank you, I'll give that a try.
