### ISSUE TITLE
OL 5.2.0  build error

### ISSUE THREAD

**Issue by yangdachu** [openlayers/openlayers#8716]
Hi @ahocevar 
angular-cli : 6.0.8
ol: 5.2.0
'ng build' is ok, but 'ng build --prod --output-hashing none' error.

ERROR in ./node_modules/ol/events/condition.js
Module build failed: Error: Debug Failure. Found typedef tag attached to node which it should not be!
    at nameForNamelessJSDocTypedef (F:\web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:13012:26)
    at getNameOfJSDocTypedef (F:\web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:13020:36)
    at Object.getNameOfDeclaration (F:\web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:13064:24)
    at Object.hasDynamicName (F:\web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:10916:23)
    at declareSymbol (F:\web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:22086:33)
...

![image](https://user-images.githubusercontent.com/23580181/46073863-a91a0c80-c1b8-11e8-95c5-9ee977068fb9.png)

**Comment by yangdachu** [comment]
@ahocevar Modified, the problem is real

**Comment by ahocevar** [comment]
Still the same issue as #8357.

**Comment by yangdachu** [comment]
@ahocevar thx
